import PageHero from '../../components/ui/PageHero';
import {useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';
import {api} from '../../api/client';

export default function ForgotPassword(){
 const [email,setEmail]=useState(''),[otp,setOtp]=useState(''),[reset,setReset]=useState(''),[pw,setPw]=useState(''),[confirm,setConfirm]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); const nav=useNavigate();
 const request=async()=>{setBusy(true);setError('');try{await api.post('/auth/forgot-password',{email});setMsg('If the email exists, a verification code has been sent.')}catch(e){setError(e.response?.data?.error?.message||'Could not send the code.')}finally{setBusy(false)}};
 const verify=async()=>{setBusy(true);setError('');try{const r=await api.post('/auth/verify-otp',{email,otp});setReset(r.data.reset_token);setMsg('Code verified. Choose a new password below.')}catch(e){setError(e.response?.data?.error?.message||'Invalid verification code.')}finally{setBusy(false)}};
 const change=async()=>{if(pw!==confirm){setError('Passwords do not match.');return;}setBusy(true);setError('');try{await api.post('/auth/reset-password',{reset_token:reset,new_password:pw});setMsg('Password reset successfully. Redirecting to login…');setTimeout(()=>nav('/login'),900)}catch(e){setError(e.response?.data?.error?.message||'Could not reset your password.')}finally{setBusy(false)}};
 return <div><PageHero eyebrow="Account recovery" title="Reset your password" subtitle="Verify your email before choosing a new password." /><div className="container-app py-10 lg:py-14"><div className="max-w-md mx-auto"><div className="card p-8"><p className="eyebrow">Account recovery</p><h1 className="text-3xl font-extrabold text-primary mt-2">Reset your password</h1><p className="muted mt-2">We'll verify your email before allowing a password change.</p>{error&&<div className="mt-5 rounded-xl bg-error-soft border border-error p-3 text-sm text-error">{error}</div>}{msg&&<div className="mt-5 rounded-xl bg-accent-soft border border-brand-100 p-3 text-sm text-accent">{msg}</div>}
 <label className="block text-sm font-bold mt-6">Email<input className="input mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button disabled={busy||!email} className="btn btn-primary w-full mt-4" onClick={request}>{busy?'Sending…':'Send verification code'}</button>
 <label className="block text-sm font-bold mt-6">Verification code<input className="input mt-2 tracking-[.3em]" inputMode="numeric" maxLength="6" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/></label><button disabled={busy||otp.length!==6} className="btn btn-outline w-full mt-3" onClick={verify}>Verify code</button>
 {reset&&<div className="mt-6 border-t pt-6"><label className="block text-sm font-bold">New password<input className="input mt-2" type="password" value={pw} onChange={e=>setPw(e.target.value)} minLength="8"/></label><label className="block text-sm font-bold mt-4">Confirm password<input className="input mt-2" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength="8"/></label><button disabled={busy||!pw||!confirm} className="btn btn-primary w-full mt-4" onClick={change}>Set new password</button></div>}
 <p className="text-sm muted text-center mt-7"><Link className="font-bold text-accent" to="/login">Back to sign in</Link></p></div></div></div></div>
}
