import PageHero from '../../components/ui/PageHero';
import { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { api } from '../../api/client';

export default function Profile() {
  const { user, setUser } = useAuth();
  const [name, setName] = useState(user?.full_name || ''); const [phone, setPhone] = useState(user?.phone || '');
  const [current, setCurrent] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState('');
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const saveProfile = async () => { setBusy(true); setError(''); setMessage(''); try { const r=await api.patch('/auth/me',{full_name:name,phone}); setUser(r.data); setMessage('Profile updated successfully.'); } catch(e) { setError(e.response?.data?.error?.message||'Could not update your profile.'); } finally { setBusy(false); } };
  const changePassword = async () => { setBusy(true); setError(''); setMessage(''); if(password!==confirm){setError('New passwords do not match.');setBusy(false);return;} try { await api.post('/auth/change-password',{current_password:current,new_password:password}); setUser({...user,must_change_password:false}); setCurrent('');setPassword('');setConfirm('');setMessage('Password changed successfully.'); } catch(e){setError(e.response?.data?.error?.message||'Could not change your password.');} finally{setBusy(false);} };
  return <div><PageHero eyebrow="Account" title="Profile & security" subtitle="Manage your account details and password securely." /><div className="container-app max-w-3xl py-10 lg:py-14">{user?.must_change_password&&<div className="rounded-xl border border-warning bg-warning-soft p-5 mb-6"><h2 className="font-extrabold text-warning">Password change required</h2><p className="text-sm text-warning mt-1">Your account was created with a temporary password. Change it below before using the rest of the platform.</p></div>}<div className="grid lg:grid-cols-2 gap-5 mt-8"><div className="card p-7"><h2 className="text-xl font-extrabold text-primary">Personal details</h2><label className="block text-sm font-bold mt-6">Full name<input className="input mt-2" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm font-bold mt-4">Email<input className="input mt-2 bg-surface-muted" value={user?.email||''} disabled/></label><label className="block text-sm font-bold mt-4">Phone<input className="input mt-2" value={phone} onChange={e=>setPhone(e.target.value)}/></label><button disabled={busy} className="btn btn-primary mt-5" onClick={saveProfile}>Save changes</button></div><div className="card p-7"><h2 className="text-xl font-extrabold text-primary">Change password</h2><p className="text-sm muted mt-2">Use at least 8 characters with a letter and a number.</p><input className="input mt-6" type="password" placeholder="Current password" value={current} onChange={e=>setCurrent(e.target.value)}/><input className="input mt-3" type="password" placeholder="New password" value={password} onChange={e=>setPassword(e.target.value)}/><input className="input mt-3" type="password" placeholder="Confirm new password" value={confirm} onChange={e=>setConfirm(e.target.value)}/><button disabled={busy||!current||!password} className="btn btn-primary mt-5" onClick={changePassword}>Change password</button></div></div>{error&&<div className="mt-5 rounded-xl bg-error-soft border border-error p-4 text-sm text-error">{error}</div>}{message&&<div className="mt-5 rounded-xl bg-accent-soft border border-brand-100 p-4 text-sm text-accent">{message}</div>}</div></div>;
}
